### ISSUE TITLE
About the implementation of ge25519_scalarmult_base_niels

### ISSUE THREAD

**Issue by yazhou71021** [TerenceGe/sr25519-donna#17]
Which document does the ge25519_scalarmult_base_niels implementation refer to ? Is it exactly the same as the scalarmult implementation of ed25519( RFC8032 5.1.4 )?

**Comment by TerenceGe** [comment]
ge25519_scalarmult_base_niels is from ed25519-donna, I think it's the same as scalarmult according to the source code (https://github.com/floodyberry/ed25519-donna/blob/8757bd4cd209cb032853ece0ce413f122eef212c/ed25519.c#L53
).
