### ISSUE TITLE
Can link with libsodium in same project?

### ISSUE THREAD

**Issue by MatthewDarnell** [TerenceGe/sr25519-donna#19]
Hi, thanks for this project, it looks great.

I am trying to link against my project which is already using libsodium. However, I'm getting many multiple reference errors in the linker:

```
$ make
clang -o substrate_test src/utils/ss58.o src/utils/crypto.o src/address.o -Wall --static -fPIC -Isrc -Ilibs/deps/include -Llibs/deps -Llibs/deps/lib -lbase58 -lfastpbkdf2 -lsr25519_donna_static -lsodium -lbc-bip39 -lbc-crypto-base  -lssl -lcrypto -pthread
/mnt/c/Users/matth/Desktop/polkadot/libs/libsodium-stable/src/libsodium/sodium/core.c:188: multiple definition of `sodium_misuse'; libs/deps/lib/libsr25519_donna_static.a(core.c.o):core.c:(.text+0x20): first defined here
/usr/bin/ld: libs/deps/lib/libsodium.a(libsodium_la-ed25519_ref10.o): in function `ge25519_scalarmult':
/mnt/c/Users/matth/Desktop/polkadot/libs/libsodium-stable/src/libsodium/crypto_core/ed25519/ref10/ed25519_ref10.c:813: multiple definition of `ge25519_scalarmult'; libs/deps/lib/libsr25519_donna_static.a(ristretto255.c.o):ristretto255.c:(.text+0xe7e0): first defined here
```

And it continues with some other functions that have been redefined.

**Comment by TerenceGe** [comment]
I'm trying to add libsodium in the example and #include <sodium.h> ,  it seems can build.
<img width="719" alt="Screen Shot 2021-09-04 at 5 25 18 PM" src="https://user-images.githubusercontent.com/1947395/132089776-d7eca62a-03a8-41c2-9e73-c4a4960674f9.png">
<img width="442" alt="Screen Shot 2021-09-04 at 5 28 35 PM" src="https://user-images.githubusercontent.com/1947395/132089777-14fe2cb0-22b3-4e0d-87fb-ec23dce05fcf.png">

Can you list the full redefined function names so I can see if I can change that?

**Comment by TerenceGe** [comment]
I've changed part of the names you mentioned, can you check if the errors disappear?

**Comment by MatthewDarnell** [comment]
I pulled the latest and linked successfully, thank you.
