### ISSUE TITLE
Generate address from mnemonic phrase

### ISSUE THREAD

**Issue by mohammad-nazari** [TerenceGe/sr25519-donna#21]
Hi my friend

Thank you for your code
I want to generate an address from a mnemonic like "unveil town glide evil true churn warfare banner agent onion uncle process".
Please Help,

Thanks,

**Comment by TerenceGe** [comment]
From mnemonic to address you need to do these steps:
1. mnemonic phrase to seed
2. seed to keypair (public key and secret key)
3. keypair to address (ss58 format)

This library is focused on the step 2 since it's private key related, you can use other library to finish step 1 and 3.

**Comment by mohammad-nazari** [comment]
So thanks.
